audit_header: false
title: Orlando Real Estate Video Blog with The Cory Lauer Group
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The -- CLIENT BRAND --, your professional -- MARKET -- Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:

client:
  name: Cory Lauer
  title: Broker Associate
  license_number: BK3051983
  name2: Tricia Williams
  title2: Broker Associate
  license_number2: BK3247673
  name3: Sunshine Collins
  title3: Executive Assistant
  license_number3:
  about_markdown: |
    The Cory Lauer Group brings a combined 38 years of real estate expertise and our agents work hard together every day to serve the needs of Southwest Florida buyers and sellers alike. Originally from Ohio, Broker Associate Cory Lauer has been a Real Estate professional since 1999. His remarkable portfolio of sales transactions has garnered him a reputation of success based on commitment to market knowledge, client's needs, and negotiation techniques. He has been honored as one of the top broker-agents in the area every year since 2009, and is on track to do it again in 2018. Tricia Williams also a Broker Associate, is a lifelong resident of Southwest Florida and has been practicing Real Estate since 2001. She has a wealth of knowledge about the market and the tri-county area and is also a licensed Home Inspector. Tricia’s contributions to The Lauer Group have been immeasurable. She primarily works with buyers and provides the customer service experience we all wish we could have throughout every transaction in our daily lives. Executive Assistant Sunshine Collins has a background in journalism, and discovered her passion for real estate in 2014. She is now devoted to obtaining her real estate license and on a mission to positively and purposefully impact the industry in major ways as she launches her real estate career. Together, they flourish as one of the most experienced and professional real estate teams in Southwest Florida and look forward to serving all of your real estate needs.
  brand: The Cory Lauer Group
  brokerage: Keller Williams
  address:
  phone: 239-444-6100
  phone_type:
  phone2:
  phone2_type:
  email:
  url: http://www.TheCoryLauerGroup.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: https://www.thecorylauergroup.com/listings-search/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/004.jpg
    CTA_title: "What’s Your -- MARKET -- Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/005.jpg
    CTA_title2: "Looking for a -- MARKET -- Home?"
    CTA_text2: "Search the entire MLS for your -- MARKET -- home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: https://www.thecorylauergroup.com/listings-search/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/TheCoryLauerGroup/
  linkedin_url: https://www.linkedin.com/in/corylauerandco
  gplus_url:
  youtube_url: http://www.youtube.com/user/CoryLauerCompany
  twitter_url: https://twitter.com/thecorylauergrp
  instagram_url: https://www.instagram.com/thecorylauergroup/
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 60
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 3px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
